---
- hosts: '{{ targethosts }}'
  remote_user: '{{ user }}'
  become: true
  vars_prompt:
    - name: "targethosts"
      prompt: "Hosts"
      default: "www.example.com"
      private: false
    - name: "user"
      prompt: "Initial User"
      default: "root"
      private: false
  roles:
    - sdarwin.bootstrap
