---
# tasks file for sdarwin.bootstrap
# installing screen and tmux, just to show that apps can be installed and ansible is functioning.
- name: install tmux
  apt: name=tmux update_cache=true
  when: ansible_os_family == 'Debian'

- name: install screen
  package: name=screen update_cache=true

- name: install libselinux-python
  package: name=libselinux-python update_cache=true
  when: ansible_os_family == 'RedHat'

- name: create ansible user
  user: name="{{ bootstrap_ansibleuser }}" shell=/bin/bash

- name: allow access to ansible for team members
  authorized_key: user=ansible
                  key="{{ item }}"
  with_items:
    - "{{ bootstrap_publickey }}"

- name: configure sudoers
  lineinfile:
    dest: /etc/sudoers.d/{{ bootstrap_ansibleuser }}
    line: "{{ bootstrap_ansibleuser }} ALL=(ALL) NOPASSWD:ALL"
    mode: 0440
    state: present
    create: true
    validate: 'visudo -cf %s'
